repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff (linter)
        entry: uv run ruff check --fix --force-exclude
        language: system
        types_or: [python, pyi]
      - id: pydocfmt-fix
        name: pydocfmt (fix)
        entry: uv run pydocfmt check --fix --force-exclude
        language: system
        types: [python]
      - id: ruff-format
        name: ruff (formatter)
        entry: uv run ruff format
        language: system
        types_or: [python, pyi, markdown]
      - id: ty
        name: ty (type checker)
        entry: uv run ty check
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest (test suite)
        entry: uv run pytest
        language: system
        pass_filenames: false

  # Example of how external users would use the published pydocformatter hooks (choose one of the two hooks):
  # - repo: https://github.com/pallgeuer/pydocformatter
  #   rev: v1.0.0
  #   hooks:
  #     - id: pydocfmt-fix
  #     - id: pydocfmt-check
  #
  # Example of how external users would use pydocformatter from a uv-managed project environment where pydocformatter is installed (choose one of the two hooks):
  # - repo: local
  #   hooks:
  #     - id: pydocfmt-fix
  #       name: pydocfmt (fix)
  #       entry: uv run pydocfmt check --fix --force-exclude
  #       language: system
  #       types: [python]
  #     - id: pydocfmt-check
  #       name: pydocfmt (check)
  #       entry: uv run pydocfmt check --force-exclude
  #       language: system
  #       types: [python]
